### PR TITLE
Works on versions 4.0.0 up to 4.0.11

### PR DESCRIPTION
**Pull request by MatthewKennedy**

### CODE REVIEW

**Comment by MatthewKennedy** [comment]
Need to write a test where the test looks for `".select2-results .select2-results__option[aria-selected]"` when the list has only one option and it is already selected.

**Comment by MatthewKennedy** [comment]
I found this to work fine for me, I added back in the attribute set to false, because I can't think of a reason why you would want to be clicking an already selected item in the drop down?

**Comment by Hirurg103** [comment]
Hi @MatthewKennedy , thank you for this PR. I decided to test select2 version `4.0.12` thoroughly and extracted all tests to the shared folder. I run all shared tests for all tested select2 versions. See [refactor tests commit](https://github.com/Hirurg103/capybara_select2/commit/2be9bf8f34b451c750f52c436418145d5e992e4d) and [add support for 4.0.9+ commit](https://github.com/Hirurg103/capybara_select2/commit/53a9bf4a39d8d8e8ed0bda47fb01146994be086c)

**Comment by MatthewKennedy** [comment]
Top work.

**Comment by Hirurg103** [comment]
Thank you!

**Pull request closed without merging**
