### PR TITLE
Use :css explicitly in #find methods

### PR DESCRIPTION
**Pull request by etipton**
- accounts for users who set `Capybara.default_selector = :xpath`

Are there other places where this is needed? (Should be harmless regardless)

### CODE REVIEW

**Comment by Hirurg103** [comment]
Hi @etipton 

> accounts for users who set Capybara.default_selector = :xpath

do you use `Capybara.default_selector = :xpath` setting?

**Comment by Hirurg103** [comment]
Hi @etipton , are you going to fix `find` in those places I mentioned?

**Comment by etipton** [comment]
? which places?

**Comment by etipton** [comment]
(sorry if I missed a GH comment somewhere)

**Comment by Hirurg103** [comment]
@etipton do you plan to complete this work? I am going to close this PR otherwise

**Comment by etipton** [comment]
@Hirurg103:

> in those places I mentioned?

Where did you mention these? I never got that message.

**Comment by etipton** [comment]
Regardless, there's work in this PR that should be helpful and not harmful, so why not merge what's here?

**Comment by Hirurg103** [comment]
@etipton I added a comment on the diff page https://github.com/Hirurg103/capybara_select2/pull/9/files

**Comment by Hirurg103** [comment]
> Regardless, there's work in this PR that should be helpful and not harmful, so why not merge what's here?

@etipton I would want to merge the complete work, not partially finished

**Comment by etipton** [comment]
Not sure if there's some kind of GitHub permissions thing happening but I can't see your comment and I never received a notification for it

**Comment by Hirurg103** [comment]
hmm, strange. OK, I will list those places there (see screenshot)

https://github.com/Hirurg103/capybara_select2/blob/66701febe7523b92bdaad8aa23c2e38bca477cab/lib/capybara_select2/utils.rb#L26

https://github.com/Hirurg103/capybara_select2/blob/66701febe7523b92bdaad8aa23c2e38bca477cab/lib/capybara_select2/helpers.rb#L38
screen shot 2019-02-21 at 8 07 33 pm


https://github.com/Hirurg103/capybara_select2/blob/66701febe7523b92bdaad8aa23c2e38bca477cab/lib/capybara_select2/helpers.rb#L43

**Comment by Hirurg103** [comment]
Hi @etipton I listed the places where it is left to fix `find` method invocations.
Could you please look at them too

**Comment by Hirurg103** [comment]
> Not sure if there's some kind of GitHub permissions thing happening but I can't see your comment and I never received a notification for it

ah, seems like I forgot to click on 'Submit review' button what's why those comments were visible to me only. Sorry, my fault!

**Comment by Hirurg103** [comment]
Hello @etipton do you plan to complete this work?

**Comment by etipton** [comment]
@Hirurg103 I'm looking now

**Comment by etipton** [comment]
@Hirurg103 done -- I also found one more place: https://github.com/Hirurg103/capybara_select2/pull/9/commits/a5a7094092c746e7c7161c02bed5d830a6a9b733#diff-7bb7a54b5fb6c5f2301ae3da6963390bR35

Thanks for your patience. I will leave to you to squash the commits when merging if that's possible.

**Comment by Hirurg103** [comment]
Hi @etipton I know, force-push is bad. I wanted to remove that empty merge-commit.

Force-push screwed all the git history, so I had to re-create the master branch (luckily I knew the hash of the master branch before I did force-push)

I do not know how to squash commits in pull-requests. Maybe you know how to do it?

I pulled your patch-1 branch, merged it into the master, squashed the commits and pulled remote branch (which created an empty merge-commit) and pushed it to the remote master

If you know how to merge remote branch without creating empty merge-commits please share it with me.

Thank you for the work!

**Comment by etipton** [comment]
@Hirurg103 

Ah, hmm. I was thinking of the "squash and merge" option, which you may need to toggle in the repo's settings? Not sure. Check out this blog post, it may have the answer: https://github.blog/2016-04-01-squash-your-commits/

**Comment by etipton** [comment]
FWIW I double-checked master and see that all of these changes are there so 👍

**Pull request closed without merging**
