### PR TITLE
Target [aria-selected='false']

### PR DESCRIPTION
**Pull request by MatthewKennedy**
Target [aria-selected='false'] to overcome issue between 4.0.5 an 4.0.9 >

### CODE REVIEW

**Comment by MatthewKennedy** [comment]
I ran the spec tests against this locally with the following Select2 versions:

- [x] 4.0.0
- [x] 4.0.1
- [x] 4.0.2
- [x] 4.0.3
- [x] 4.0.4
- [x] 4.0.5
- [x] 4.0.6
- [x] 4.0.7
- [x] 4.0.8
- [x] 4.0.9
- [x] 4.0.10
- [x] 4.0.11

**Comment by MatthewKennedy** [comment]
Fails if only one option.

**Comment by Hirurg103** [comment]
could you please configure your app to use your fork for now?

**Comment by MatthewKennedy** [comment]
I found an issue I am looking into.

**Pull request closed without merging**
