### PR TITLE
Select2 v4.0.9 support

### PR DESCRIPTION
**Pull request by aTei**
Not working for prev v4.0.* versions

https://github.com/select2/select2/releases/tag/4.0.9
Related commit https://github.com/select2/select2/pull/5582

### CODE REVIEW

**Comment by aTei** [comment]
Updated info

**Comment by Hirurg103** [comment]
Hi @aTei , thank you for this contribution.

I think that if I merge this PR the gem won't work for select2 v4.0.5? Any ideas?

**Comment by aTei** [comment]
The only option I see is to make it the same way as was done separation between 2, 3 & 4

**Comment by Hirurg103** [comment]
Let me think a bit

**Comment by Hirurg103** [comment]
> The only option I see is to make it the same way as was done separation between 2, 3 & 4

Yea, could you go with this solution for now and add one test case for version v4.0.10 in a separate test file (`select2_v4-0-10_spec.rb` for example). And change version in `spec/fixtures/select2-v4/index.html` back to v4.0.5

**Comment by tbk303** [comment]
Maybe omit `[role='treeitem']` in the selector and add a check for `[role='alert']` to filter the messages issued by select2?

**Comment by MatthewKennedy** [comment]
Any chance this can make it as a released version?

**Comment by Hirurg103** [comment]
@MatthewKennedy, this PR cannot be merged now because it breaks support for previous versions of select2 (v4.0.5 for example)

**Comment by Hirurg103** [comment]
Hi @aTei , thank you for this contribution. I decided to test select2 version `4.0.12` thoroughly and extracted all tests to the shared folder. I run all shared tests for all tested select2 versions. See [refactor tests commit](https://github.com/Hirurg103/capybara_select2/commit/2be9bf8f34b451c750f52c436418145d5e992e4d) and [add support for 4.0.9+ commit](https://github.com/Hirurg103/capybara_select2/commit/53a9bf4a39d8d8e8ed0bda47fb01146994be086c)

**Pull request closed without merging**
