### PR TITLE
Remove [role='treeitem']

### PR DESCRIPTION
**Pull request by MatthewKennedy**
This is possibly slightly excessive targeting, that's causing issues between v 4.5 and 4.9 >

### CODE REVIEW

**Comment by MatthewKennedy** [comment]
Depending how the tests run, targeting this specific may just adding an unnecessary point of failure between different versions of Select2 version 4.x.

**Comment by dgilperez** [comment]
I'm experiencing this same problem after upgrading to select2 4.0.13 - any reason to close this?

**Comment by Hirurg103** [comment]
Hi @dgilperez, did you try to upgrade the gem? See [this issue](https://github.com/Hirurg103/capybara_select2/issues/21) for the reason why this PR has been closed

**Comment by Hirurg103** [comment]
Hi @dgilperez, did you try to upgrade the gem? See [this issue](https://github.com/Hirurg103/capybara_select2/issues/21) for the reason why this PR has been closed

**Comment by dgilperez** [comment]
Hi @Hirurg103, thanks for the quick response! 

Yes, I did, but my specs where still red. For same reason the `aria-selected=false` was not working either. We're using now this patch https://github.com/dgilperez/capybara_select2/commit/42b069cef1b85e72be4d9903cc78c4e58bec10b1, and facing some `Ambiguous match, found 2 elements matching visible css` errors now. 

We're using select2 4.0.13.

**Comment by dgilperez** [comment]
Maybe I should open a new issue to limit / redirect the noise?

**Comment by MatthewKennedy** [comment]
@dgilperez Whats the example of your HTML that you're targeting, and the code in the test you're running?

**Comment by dgilperez** [comment]
Hi @MatthewKennedy, 

I ended up needing this selector, which I have in my local fork.

```
'4' => ".select2-results .select2-results__option[role=option]"
```

The error was about results not found with current gem's selector, and failing by finding multiple when using the `".select2-results .select2-results__option"` selector. I'm sorry I don't have the exact HTML, I just moved forward. 

I'm guessing this is due to select2 playing with option attributes from version to version ... maybe another approach could be needed?

**Comment by Hirurg103** [comment]
@dgilperez in `4.0.3` version of the gem is used `".select2-results .select2-results__option[aria-selected='false']"` option selector.

> For same reason the `aria-selected=false` was not working either. 

With what error it was failing for you?

**Comment by dgilperez** [comment]
The error is 

```
     Capybara::ElementNotFound:
       Unable to find css ".select2-results .select2-results__option[aria-selected='false']" within #<Capybara::Node::Element tag="body" path="/HTML/BODY[1]">
```

When I change to my fork, it's green.

**Comment by MatthewKennedy** [comment]
From the information above I can only assume that you are trying to select an already selected item. 

Hence there won’t be a selected false on the element you are targeting.

**Comment by MatthewKennedy** [comment]
In version 4.X if you have a multiple item selector and you click on an item that is already selected it de-selects that item.

This behaviour didn’t happen in previous versions.

Something to be aware of.

**Comment by dgilperez** [comment]
Ok, thanks a lot @MatthewKennedy. While I don't see that happening in my spec (selecting twice), that could be the case. I have the specs working for now so we're moving forward, but I'll link this thread in the code in case we need to revisit / to avoid more noise from our side. Thanks again!

**Comment by MatthewKennedy** [comment]
@Hirurg103 if you remove the empty `<option></option>` tags in the index.html.erb spec support file you will run into the issue:
` Unable to find css ".select2-results .select2-results__option[aria-selected=false]" within #<Capybara::Node::Element tag="body" path="/HTML/BODY[1]">`

I believe this is coming from the rails select tag set to: `include_blank: false`

Using
`".select2-results .select2-results__option[aria-selected]"` will get around this but may lead to `Ambiguous match, found 2 elements matching visible css`

What do you think?

**Comment by MatthewKennedy** [comment]
@dgilperez Does your rails select tag have `include_blank: false` set?

**Comment by Hirurg103** [comment]
> @Hirurg103 if you remove the empty `<option></option>` tags in the index.html.erb spec support file you will run into the issue:
> ` Unable to find css ".select2-results .select2-results__option[aria-selected=false]" within #<Capybara::Node::Element tag="body" path="/HTML/BODY[1]">`

@MatthewKennedy thanks for the catch, I will try it

**Comment by dgilperez** [comment]
> @dgilperez Does your rails select tag have `include_blank: false` set?

We're using simple_form, and this is the particular input code failing: 

```
        = f.input :author_ids,
            as: :select,
            collection: [],
            label: false,
            hint: hint_text,
            input_html: { multiple: true,
                          data: { provider: 'propose-user-names',
                                  url: users_path,
                                  values: some_json_collection }}
```

The select2 functionality is provided by the data-behaviour.

**Comment by Hirurg103** [comment]
@dgilperez hope [this commit](https://github.com/Hirurg103/capybara_select2/commit/d6c9a91aad9177e781b5c483121bf4f4bb6d2d31) helps to fix the issue for you. I will try to release the new version of the gem asap

**Pull request closed without merging**
