### PR TITLE
Fix Ruby 2.7 deprecation warning

### PR DESCRIPTION
**Pull request by lucascaton**
Fixes issue #24 :)

### CODE REVIEW

**Comment by Hirurg103** [comment]
Hi @lucascaton , thank you for your PR. Looks like tests are failing on CI. I am looking into it now

**Comment by Hirurg103** [comment]
Thanks again for your contribution to this project @lucascaton !

**Comment by lucascaton** [comment]
Thanks @Hirurg103!
Are you planning to release a new version soon? Thanks! 😃

**Comment by Hirurg103** [comment]
Hi @lucascaton , I will release a new version most likely this weekend

**Comment by lucascaton** [comment]
@Hirurg103 thank you!

**Comment by lucascaton** [comment]
Hi @Hirurg103 - could you please release a new version?

**Comment by Hirurg103** [comment]
Hi @lucascaton , done. Sorry for the delay

**Comment by lucascaton** [comment]
Thanks, @Hirurg103! 😃

**Pull request merged**
